# Generated by Django 2.1.5 on 2019-01-12 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0003_promotion_promotion_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='location',
        ),
    ]
