# Generated by Django 2.1.5 on 2019-01-12 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0004_remove_restaurant_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='facebook_id',
            field=models.CharField(default='347472895881485', max_length=100),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurant_url',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='restaurant_name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
