# Generated by Django 2.1.5 on 2019-01-12 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('models', '0005_auto_20190112_2148'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='image',
            field=models.ImageField(default='default2.jpg', upload_to='promotion_pic'),
        ),
        migrations.AddField(
            model_name='restaurant',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='restaurant_pic'),
        ),
    ]
